# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_job'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='Job',
        ),
    ]
