# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180823_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_type',
            field=models.CharField(blank=True, choices=[('IT', 'It'), ('FINANCIAL', 'Financial'), ('SPACE', 'Space'), ('SPIRITUAL', 'Spiritual')], max_length=50, null=True),
        ),
    ]
