# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_job_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
