# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180824_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_type',
            field=models.CharField(blank=True, choices=[('IT', 'It'), ('FINANCIAL', 'Financial'), ('SPACE', 'Space'), ('SPIRITUAL', 'Spiritual')], max_length=127, null=True),
        ),
    ]
